### ISSUE TITLE
bug: OIDC authentication gets UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by ixxeL2097** [homarr-labs/homarr#2408]
### Describe the bug

I'm trying to setup Homarr with Authentik OIDC. I use Homarr official Helm chart and try to get the OIDC working but whatever my configuration is, I always end up with CA CERT issue. I tried to upload Authentik Self Signed certificate for OIDC and also my CA chain but it never work. 

```js
2025-02-23T18:46:26.778Z error: TypeError: fetch failed
  at node:internal/deps/undici/undici:13502:13
  at async n1 (/app/apps/nextjs/.next/server/chunks/4687.js:489:50086)
  at async n3 (/app/apps/nextjs/.next/server/chunks/4687.js:489:52860)
  at async n8 (/app/apps/nextjs/.next/server/chunks/4687.js:489:55276)
  at async oe (/app/apps/nextjs/.next/server/chunks/4687.js:489:57629)
  at async d (/app/apps/nextjs/.next/server/app/api/auth/[...nextauth]/route.js:1:3432)
  at async tr.do (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:17582)
  at async tr.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:22212)
  at async doRender (/app/node_modules/next/dist/server/base-server.js:1452:42)
The above error also had these properties on it:
{
  cause: [Error: unable to get local issuer certificate] {
    code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
  }
}
2025-02-23T18:46:26.779Z error: Error: unable to get local issuer certificate
The above error also had these properties on it:
{ code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
2025-02-23T18:46:26.804Z info: tRPC request from server-fetch by user 'undefined (undefined)'
2025-02-23T18:46:26.818Z info: tRPC request from server-fetch by user 'undefined (undefined)'
2025-02-23T18:46:26.886Z info: ➖ Connection (2) 1001
2025-02-23T18:46:27.056Z info: ➕ Connection (3) GET /websockets
2025-02-23T18:46:27.057Z info: tRPC request from unknown by user 'undefined (undefined)'
```

### Steps to reproduce

Here is my configuration : 

Homarr: v1.7.0 
Helm chart: 2.8.0
Authentik: 2024.12.3

values.yaml :
```yaml
homarr:
  env:
    AUTH_PROVIDERS: "credentials,oidc"
    AUTH_SESSION_EXPIRY_TIME: "1h"
    AUTH_OIDC_AUTO_LOGIN: "false"
    AUTH_OIDC_ISSUER: "https://authentik.example.com/application/o/homarr/"
    AUTH_OIDC_CLIENT_NAME: "Authentik"
    AUTH_OIDC_SCOPE_OVERWRITE: "openid email profile groups"
    AUTH_OIDC_GROUPS_ATTRIBUTE: "groups"
    AUTH_LOGOUT_REDIRECT_URL: "https://homarr.example.com/auth/login"

  envSecrets:
    authOidcCredentials:
      existingSecret: "auth-oidc-secret"
      oidcClientId: "oidc-client-id"
      oidcClientSecret: "oidc-client-secret"
    dbCredentials:
      existingSecret: "db-secret"
      dbEncryptionKey: "db-encryption-key"
```

### Impact

I cannot login with OIDC in any way with a personal CA or self signed certificate

### Version

1.6.0

### Installation method

Helm

### Browser

Chrome

**Comment by Meierschlumpf** [comment]
You can use `NODE_EXTRA_CA_CERTS` to set the additional certificate. You can for example upload the certificate in the trusted certificates and. So when your certificate-file is `authentik.crt` you can use it with `NODE_EXTRA_CA_CERTS="/appdata/trusted-certificates/authentik.crt"`
I got that from https://github.com/nextauthjs/next-auth/issues/3580

**Comment by ixxeL2097** [comment]
Ok so I tried that, and it didn't work actually. I tried both with the actual cert from Authentik URL and also its own self signed certificate used for OIDC.

Added parameter : 
```yaml
homarr:
  env:
    NODE_EXTRA_CA_CERTS: "/appdata/trusted-certificates/authentik.crt"
```

The cert is uploaded with WEB UI and I double checked that the container has it : 

```bash
homarr-k0s-6f78b8d7b-2twhd:/app# ls -la /appdata/trusted-certificates/
total 12
drwxr-xr-x    2 root     root          4096 Feb 23 19:10 .
drwxr-xr-x    5 root     root          4096 Feb 23 19:07 ..
-rw-r--r--    1 root     root          3104 Feb 23 19:10 authentik.crt
``` 
Same error as previously actually. 

I also tried with :
```env
NODE_TLS_REJECT_UNAUTHORIZED: "0"
```
and it actually worked well but it's not secure at all !!

**Comment by Meierschlumpf** [comment]
Okay I found a way to configure it correctly with a code change. We can override the fetch it is using: https://authjs.dev/guides/corporate-proxy?framework=next-js

I implemented this change on the `use-certificates-for-oidc` branch. You can try out if it works for you on the image with the same name

**Comment by Meierschlumpf** [comment]
You will only need to have the certificate in the trusted-certificates directory / uploaded on the certificates management site. No need for a custom env variable anymore

**Comment by ixxeL2097** [comment]
@Meierschlumpf ok I tried this (image: `ghcr.io/homarr-labs/homarr:use-certificates-for-oidc` and certificates uploaded and located in `/appdata/trusted-certificates/`) but I'm afraid I still get the same error unfortunately 🤕 
No difference in logs. I still need to get the `NODE_TLS_REJECT_UNAUTHORIZED` for the moment. Feel free to request any test from my side if you need to.

**Comment by ixxeL2097** [comment]
I think it broke something. I had to re-install a new SQLite DB since it broke it (no worries for that its fine for me, I'm just saying to help troubleshooting 😄 )

Here are some of the logs I got : 
```node
2025-02-24T20:20:39.601Z [32minfo[39m: Successfully fetched 14562 icons from 6 repositories within 527 ms
2025-02-24T20:20:39.693Z [32minfo[39m: Updating icons in database...
2025-02-24T20:20:47.367Z [32minfo[39m: Completed healthcheck after 12.436154999999417ms
2025-02-24T20:20:50.457Z [32minfo[39m: Updated database within one second (-0, +0)
2025-02-24T20:20:50.457Z [33mwarn[39m: The callback of 'iconsUpdater' succeeded but took 1386.14ms longer than expected (10000ms). This may indicate that your network performance, host performance or something else is too slow. If this happens too often, it should be looked into.
2025-02-24T20:20:50.502Z [32minfo[39m: Starting schedule of cron job ping.
2025-02-24T20:20:50.504Z [32minfo[39m: Cleared previous ping urls
2025-02-24T20:20:50.504Z [32minfo[39m: Starting schedule of cron job smartHomeEntityState.
2025-02-24T20:20:50.504Z [32minfo[39m: Starting schedule of cron job mediaServer.
2025-02-24T20:20:50.504Z [32minfo[39m: Starting schedule of cron job mediaOrganizer.
2025-02-24T20:20:50.504Z [32minfo[39m: Starting schedule of cron job downloads.
2025-02-24T20:20:50.504Z [32minfo[39m: Starting schedule of cron job dnsHole.
2025-02-24T20:20:50.504Z [32minfo[39m: Starting schedule of cron job mediaRequestStats.
2025-02-24T20:20:50.505Z [32minfo[39m: Starting schedule of cron job mediaRequestList.
2025-02-24T20:20:50.505Z [32minfo[39m: Starting schedule of cron job rssFeeds.
2025-02-24T20:20:50.505Z [32minfo[39m: Starting schedule of cron job indexerManager.
2025-02-24T20:20:50.505Z [32minfo[39m: Starting schedule of cron job healthMonitoring.
2025-02-24T20:20:50.505Z [32minfo[39m: Starting schedule of cron job sessionCleanup.
2025-02-24T20:20:50.512Z [32minfo[39m: Starting schedule of cron job updateChecker.
2025-02-24T20:20:50.532Z [32minfo[39m: Dispatching request https://api.github.com/repos/homarr-labs/homarr/releases (5 headers)
2025-02-24T20:20:50.827Z [32minfo[39m: Update checker found a new available version: v1.7.0. Current version is 1.7.0
2025-02-24T20:20:50.829Z [32minfo[39m: Starting schedule of cron job mediaTranscoding.
2025-02-24T20:20:50.829Z [32minfo[39m: Starting schedule of cron job minecraftServerStatus.
2025-02-24T20:20:52.638Z [32minfo[39m: tRPC request from server-fetch by user 'admin (eh21ayx21y052wix3kebkped)'
2025-02-24T20:20:52.710Z [32minfo[39m: tRPC request from server-fetch by user 'admin (eh21ayx21y052wix3kebkped)'
2025-02-24T20:20:52.877Z [32minfo[39m: tRPC request from rsc by user 'admin (eh21ayx21y052wix3kebkped)'
 ⨯ Error [TRPCError]: no such column: "column_count" - should this be a string literal in single-quotes?
    at I.prepareQuery (.next/server/chunks/3643.js:164:94675)
    at QueryPromise._prepare (.next/server/chunks/3643.js:170:88727)
    at QueryPromise.executeRaw (.next/server/chunks/3643.js:170:89303)
    at QueryPromise.execute (.next/server/chunks/3643.js:170:89374)
    at QueryPromise.then (.next/server/chunks/3643.js:170:54874) {
  code: 'INTERNAL_SERVER_ERROR',
  digest: '1024292654',
  [cause]: SqliteError: no such column: "column_count" - should this be a string literal in single-quotes?
      at I.prepareQuery (.next/server/chunks/3643.js:164:94675)
      at QueryPromise._prepare (.next/server/chunks/3643.js:170:88727)
      at QueryPromise.executeRaw (.next/server/chunks/3643.js:170:89303)
      at QueryPromise.execute (.next/server/chunks/3643.js:170:89374)
      at QueryPromise.then (.next/server/chunks/3643.js:170:54874) {
    code: 'SQLITE_ERROR'
  }
}
 ⨯ Error [TRPCError]: no such column: "column_count" - should this be a string literal in single-quotes?
    at I.prepareQuery (.next/server/chunks/3643.js:164:94675)
    at QueryPromise._prepare (.next/server/chunks/3643.js:170:88727)
    at QueryPromise.executeRaw (.next/server/chunks/3643.js:170:89303)
    at QueryPromise.execute (.next/server/chunks/3643.js:170:89374)
    at QueryPromise.then (.next/server/chunks/3643.js:170:54874) {
  code: 'INTERNAL_SERVER_ERROR',
  digest: '1024292654',
  [cause]: SqliteError: no such column: "column_count" - should this be a string literal in single-quotes?
      at I.prepareQuery (.next/server/chunks/3643.js:164:94675)
      at QueryPromise._prepare (.next/server/chunks/3643.js:170:88727)
      at QueryPromise.executeRaw (.next/server/chunks/3643.js:170:89303)
      at QueryPromise.execute (.next/server/chunks/3643.js:170:89374)
      at QueryPromise.then (.next/server/chunks/3643.js:170:54874) {
    code: 'SQLITE_ERROR'
  }
}
2025-02-24T20:20:53.019Z [32minfo[39m: ➕ Connection (1) GET /websockets
2025-02-24T20:20:53.021Z [32minfo[39m: tRPC request from unknown by user 'undefined (undefined)'
2025-02-24T20:20:53.557Z [32minfo[39m: ➕ Connection (2) GET /websockets
2025-02-24T20:20:53.573Z [32minfo[39m: tRPC request from unknown by user 'admin (eh21ayx21y052wix3kebkped)'
2025-02-24T20:20:55.517Z [31merror[39m: Failed to run job 'mediaServer': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:20:55.524Z [31merror[39m: Failed to run job 'downloads': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:20:55.524Z [31merror[39m: Failed to run job 'dnsHole': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:20:55.525Z [31merror[39m: Failed to run job 'healthMonitoring': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:20:57.305Z [32minfo[39m: Completed healthcheck after 1.6038260000023001ms
2025-02-24T20:21:00.513Z [31merror[39m: Failed to run job 'smartHomeEntityState': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:00.514Z [31merror[39m: Failed to run job 'mediaServer': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:00.523Z [31merror[39m: Failed to run job 'mediaOrganizer': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:00.523Z [31merror[39m: Failed to run job 'downloads': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:00.523Z [31merror[39m: Failed to run job 'dnsHole': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:00.523Z [31merror[39m: Failed to run job 'mediaRequestStats': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:00.523Z [31merror[39m: Failed to run job 'mediaRequestList': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:00.525Z [31merror[39m: Failed to run job 'healthMonitoring': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:05.512Z [31merror[39m: Failed to run job 'mediaServer': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:05.519Z [31merror[39m: Failed to run job 'downloads': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:05.520Z [31merror[39m: Failed to run job 'dnsHole': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:05.520Z [31merror[39m: Failed to run job 'healthMonitoring': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:07.305Z [32minfo[39m: Completed healthcheck after 1.106316000001243ms
2025-02-24T20:21:10.513Z [31merror[39m: Failed to run job 'mediaServer': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:10.517Z [31merror[39m: Failed to run job 'downloads': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:10.521Z [31merror[39m: Failed to run job 'dnsHole': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:10.521Z [31merror[39m: Failed to run job 'healthMonitoring': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:15.515Z [31merror[39m: Failed to run job 'mediaServer': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:15.521Z [31merror[39m: Failed to run job 'downloads': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:15.521Z [31merror[39m: Failed to run job 'dnsHole': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:15.525Z [31merror[39m: Failed to run job 'healthMonitoring': SqliteError: no such column: "section_id" - should this be a string literal in single-quotes?
2025-02-24T20:21:17.304Z [32minfo[39m: Completed healthcheck after 0.9698399999979301ms
2025-02-24T20:21:19.147Z [32minfo[39m: ➕ Connection (3) GET /websockets
2025-02-24T20:21:19.151Z [32minfo[39m: tRPC request from unknown by user 'admin (eh21ayx21y052wix3kebkped)'
2025-02-24T20:21:19.182Z [32minfo[39m: ➕ Connection (4) GET /websockets
2025-02-24T20:21:19.187Z [32minfo[39m: tRPC request from unknown by user 'admin (eh21ayx21y052wix3kebkped)'
2025-02-24T20:21:19.211Z [32minfo[39m: ➕ Connection (5) GET /websockets
2025-02-24T20:21:19.214Z [32minfo[39m: tRPC request from unknown by user 'admin (eh21ayx21y052wix3kebkped)'
```

**Comment by Meierschlumpf** [comment]
Oh yeah makes sense, sorry. The branch I gave you an image has changes that will be published in the next version (1.8.0) on friday with database changes. So when you switched back it had problems.

Okay intressting that it did not work. Did you get exactly the same error? or only one looking similar?

**Comment by ixxeL2097** [comment]
Yea exactly the same error ! I imported all certificates from my internal local domain (Root CA chain + wildcards) and also the Authentik Self signed just to be sure to have everything need, but always the same error.  Actually the certificates import work for Integrations endpoints, so I can confirm that somehow Homarr uses certificates for that purpose, but it looks like it ignore them for OIDC.

**Comment by Meierschlumpf** [comment]
Can you try the following things:

1. try without trailing slash for the issuer
2. open your issuers well-known path: https://authentik.example.com/application/o/homarr/.well-known/openid-configuration and check the certificate:

to check the certificate, click on your browsers url bar beside the url, then 🔒 connection is secure
![Image](https://github.com/user-attachments/assets/26a0c582-1ccd-436b-8f2c-406457a8eaca)
and after that certificate is secure
![Image](https://github.com/user-attachments/assets/207dbc2d-5a13-4f53-b2fb-d5db97a69a90)
That then should show you the current certificate:
![Image](https://github.com/user-attachments/assets/9316da95-d6b7-44af-ac9d-308c9fd3bb9f)

Under details you find the hierarchy with all intermediate and root certificates. Try to upload them all and try again

**Comment by ixxeL2097** [comment]
So here is what I tried. 

I have my own CA with Root and Intermediate CA. The Authentik's certificate comes from the intermediate CA and is a wildcard certificate.

![Image](https://github.com/user-attachments/assets/0723357a-146b-4cdd-a865-28f9a2bf7978)

So I uploaded Root and Intermediate CA to Homarr, and even the wildcard certificate. First I tried Root and Int CA as a single certificate and also separately.

![Image](https://github.com/user-attachments/assets/293f6724-4833-4355-ba44-814c805b4e05)

I tried this with both `use-certificates-for-oidc` and `v1.7.0` version but it gives me the same error each time : 

```node
2025-02-27T19:45:55.839Z error: TypeError: fetch failed
  at node:internal/deps/undici/undici:13502:13
  at async oV (/app/apps/nextjs/.next/server/chunks/5879.js:489:50086)
  at async oq (/app/apps/nextjs/.next/server/chunks/5879.js:489:52860)
  at async oZ (/app/apps/nextjs/.next/server/chunks/5879.js:489:55276)
  at async o0 (/app/apps/nextjs/.next/server/chunks/5879.js:489:57629)
  at async d (/app/apps/nextjs/.next/server/app/api/auth/[...nextauth]/route.js:1:3658)
  at async tr.do (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:17582)
  at async tr.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:22212)
  at async doRender (/app/node_modules/next/dist/server/base-server.js:1452:42)
The above error also had these properties on it:
{
  cause: [Error: unable to get local issuer certificate] {
    code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
  }
}
2025-02-27T19:45:55.841Z error: Error: unable to get local issuer certificate
The above error also had these properties on it:
{ code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
2025-02-27T19:45:55.864Z info: tRPC request from server-fetch by user 'undefined (undefined)'
2025-02-27T19:45:55.873Z info: tRPC request from server-fetch by user 'undefined (undefined)'
```

I have to mention that I have this setup for other servers inside my lab and it works with OIDC and these CA chains, for example with Hashicorp Vault and others. I tried without the trailing slash for the `AUTH_OIDC_ISSUER` variable but sadly it doesn't help :/

**Comment by Meierschlumpf** [comment]
Okay you can try again. This time it should also log the dispatched requests in the format `Dispatching request https://<full-url> (<count> headers)`
Don't forget to update the image and pull the latest version of the tag `use-certificates-for-oidc`

**Comment by ixxeL2097** [comment]
Ok, I think it worked this time. I removed the `NODE_TLS_REJECT_UNAUTHORIZED: '0'` parameter and pulled your updated image and this time I can login with OIDC without any error. So I think you got it dude 🚀

**Comment by ixxeL2097** [comment]
Do you have any idea when the next version with this patch will be released ? I would like to not roll back at the moment in order to keep my current database

**Comment by Meierschlumpf** [comment]
Okay that's good to hear. It kind of depends. We might make a release in the upcoming week beside the weekly release on friday, because of the pi-hole v6 and some design changes. For now I'm gonna mark the pull request as ready and request a review from one of my colleagues. Thank you for trying it out!

**Comment by ixxeL2097** [comment]
Great ! Thank you too for your hard work 🚀
